### ISSUE TITLE
v2 GUI changes

### ISSUE THREAD

**Issue by mmikeww** [Uberi/Yunit#18]
@hoppfrosch 

I just saw your new commits with the branches. The v2-078 is still compatible with the old GUI syntax. The new GUI build is only a test build that hasn't yet been released as an alpha release yet (but will probably be 079). It doesn't look like they will be cross-compatible, but I wonder if we can do `if (A_AhkVersion < 2)` like in the past (https://github.com/Uberi/Yunit/commit/25bc1dd4224872b5f8e9be8cf7af4a2e28a164c0) so that we don't have to have two separate branches. That would be preferable

**Comment by hoppfrosch** [comment]
> The v2-078 is still compatible with the old GUI syntax
Is this really true? 

At least YUnit doesn't run anymore with AutoHotkey 2.0-a78 within my environment. I took this as reason to switch over to new syntax (well knowing it isn't stable anymore). As I probably will only use V2 in the future, I'm not really interested in supporting a "multi-version" variant of _window.ahk_.

As far as I've seen it might be difficult to use  `if (A_AhkVersion < 2)`.

But supplying two variants of window.ahk within the main branch might be an alternative.

**Comment by mmikeww** [comment]
078 made some changes to MsgBox and InputBox, maybe something like that got broken:
https://autohotkey.com/boards/viewtopic.php?f=37&t=2120&p=138141#p138141

**Comment by hoppfrosch** [comment]
So what's our agreement now?

Keeping V2.0-a78 changes on a separate branch until V2.0-a78 syntax changes leave pre-alpha stage? 
Maintaining two versions of `window.ahk` afterwards - one for AHK 1.1 to AHK 2.0-a77 and the other for after AHK  2.0-a77?
----
After all what I've seen, I like the new GUI-interface of AHK 2.0-a78 much more than the older one (it was alway a pain for me wrinting GUI in AHK ... ;-)) - so probably when it get's more stable, I won't go back to an older version. I don't mind using an 2.0-alpha version as it seems to converge and has a little update frequency. Porting `Window.ahk` to the new syntax was just my first exercise, to examinate the new syntax ... (and check the efforts of porting)

**Comment by mmikeww** [comment]
I think its fine to leave it as two branches for now. We can revisit it later when the syntax is finalized
