### ISSUE TITLE
Line number of failed test

### ISSUE THREAD

**Issue by trashner** [Uberi/Yunit#21]
I noticed the line number that is shown for a failed test refers to the 'Yunit.ahk' file, and not the actual test suite file.

E.g. `Line #85: FAIL` or `Line #60: ExpectedException`

Is this by design?

**Comment by mmikeww** [comment]
I've noticed this too. I tried to fix it at one point, but never figured it out

**Comment by trashner** [comment]
Think I got it. Change line #85 in 'Yunit.ahk' from `throw Exception(Message, -1)` to `throw Exception(Message, -2)`.

`-2` goes one entry down the call stack and therefor reports back the line number of the actual test script.

**Comment by hoppfrosch** [comment]
Thanks for pointing this out - will fix ASAP
