### ISSUE TITLE
V2 Gui Changes by AutoHotkey v2.0-a103-56441b52

### ISSUE THREAD

**Issue by hoppfrosch** [Uberi/Yunit#27]
AHK v2.0-a103-56441b52 (or some eralier versions) introduced some incompatible changes in GUI commands:

- SetFont() now uses 2 arguments (1 separate argument for Font)
- Title() was introduced (splitted from Show())

Therefore Window.ahk throws error when usuing it.

-> This should be fixed

**Comment by mmikeww** [comment]
Ok I'll take a look. 

Not sure why @lexikos didn't include these changes in the V2 UPDATES thread on the forum..

**Comment by hoppfrosch** [comment]
Thanks - had fixed it myself, but wasn't able to push to github through VPN/ssh channel I am using these days ...

**Comment by Lexikos** [comment]
I don't believe that `MyGui.SetFont("s16, Arial")`  ever worked. SetFont has taken two parameters from the very beginning. See Lexikos/AutoHotkey_L@30a993d0. As far as I can recall, no GUI command or function has ever had comma-delimited options that weren't actual parameters (maybe excluding list values after Gui Delimiter has been used).

The Title parameter of Show was removed by Lexikos/AutoHotkey_L@779d8915 prior to v2.0-a079, which was the first release including the GUI objects. Only scripts written for fincs' build allowed title to be specified that way.

**Comment by hoppfrosch** [comment]
@Lexikos: Never noticed that `SetFont()` has a separate Parameter for Fontname. The syntax above worked until recently: therefore at least anything else has to be changed in this case...
But that doesn't matter - the error above was detected by the parser and after the fix everything works fine

**Comment by Lexikos** [comment]
The invalid options were ignored, but it never *worked*; i.e. did not set the font family.

Helgef added validation to some functions. This is probably one of them.
