### ISSUE TITLE
combine all the output modules into one file?

### ISSUE THREAD

**Issue by mmikeww** [Uberi/Yunit#30]
Instead of having to #include multiple files and modules, why don't we just put all of the output module classes into the main Yunit.ahk file, and then we only need one line of #include ? Anyone see a problem with that? @hoppfrosch @Lexikos

**Comment by hoppfrosch** [comment]
I don't have principal objections  but I am not a big fan of having all output modules in one file ...

Reason: Having all in one file you have to include all output modules at once. As stated in https://github.com/Uberi/Yunit/pull/29 YUnit could be made compatible for AHK a104 without making all the output modules compatible as well: if I'am fine with not using windows module, I can go with a104 - having all the output modules in one file I cannot.

**Comment by mmikeww** [comment]
very good point

**Comment by Lexikos** [comment]
I don't use any of the provided output modules; I only `#include <Yunit\Yunit>`.

**Comment by hoppfrosch** [comment]
Closed as there is no real reason to combine all the modules into one.
