### ISSUE TITLE
Result.line and Result.file always point to main Yunit.ahk

### ISSUE THREAD

**Issue by mmikeww** [Uberi/Yunit#31]
the output modules check the `result.line` and `result.file` to give the user more information, but these always point to the main Yunit.ahk file, which is useless in helping to quickly find the location of the assertion fail

**Comment by mmikeww** [comment]
see also Issue #21 
it looks like maybe AHK changed the call stack at some point, because the exception now needs to be back to `-1`

**Comment by mmikeww** [comment]
@hoppfrosch  am i doing something wrong? it looks like you fixed issue #21 in commit 49f0f3b26f9 but on my machine, i need `-1` in order to get the correct line number. `-2` shows the Yunit.ahk line number

**Comment by hoppfrosch** [comment]
Sorry for the much to late answer .... lost this project out of focus.

Verified that -1 is the correct value with AutoHotkey v2.0beta1. Cannot comprehend when call stack was changed.
