### ISSUE TITLE
v2beta1 no longer has OwnMethods()

### ISSUE THREAD

**Issue by mmikeww** [Uberi/Yunit#33]
i'm trying to update the `v2` branch to support v2-beta1, but getting this error:

![image](https://user-images.githubusercontent.com/1900684/127815686-19f57246-ac36-497f-90a0-90fded1d4569.png)

according to this link:
https://www.autohotkey.com/boards/viewtopic.php?f=37&t=86283
> Methods and properties are merged once again, so the following were removed: ObjOwnMethods, DefineMethod, DeleteMethod, HasOwnMethod, OwnMethods.

So I'm not really sure how to update this file here:
https://github.com/Uberi/Yunit/blob/baf809c4ecda56ab9090449d737c9c0334b5fa4c/Yunit.ahk#L45

@Lexikos or @sswwaagg can you advise?

initially Lexikos added the changes in this commit:  https://github.com/Uberi/Yunit/commit/21591c563f37cbaa838cbd529f6062dbe1ea9c2f

and the comparable v1 code here:
https://github.com/Uberi/Yunit/blob/master/Yunit.ahk#L44

**Comment by infogulch** [comment]
Hi out of the blue. :) The key lines in that commit may be:

```diff
-        for k,v in cls
+        for k,v in cls.prototype.OwnMethods()
         {
-           if Type(v) = "Func" ;test
```

The purpose of the loop is to iterate all the methods (tests) and call them. I guess `OwnMethods` is a shortcut to get just the methods out of the prototype, so to do it without `OwnMethods` I suppose just iterating the prototype keys and checking if their corresponding values are functions is enough.

**Comment by mmikeww** [comment]
this line also probably needs to be changed:

https://github.com/Uberi/Yunit/blob/baf809c4ecda56ab9090449d737c9c0334b5fa4c/Yunit.ahk#L22

I tried changing to `this("")` but i get an error "Yunit.Tester has no method defined for Call"

**Comment by mmikeww** [comment]
making progress
