### ISSUE TITLE
line numbers off

### ISSUE THREAD

**Issue by mmikeww** [Uberi/Yunit#34]
the fix in this commit

https://github.com/Uberi/Yunit/commit/49f0f3b26f954286567bf1754e33051605222969

i know that that fix works in some cases

but sometimes i need to change it back to -1 to work

**Comment by mmikeww** [comment]
looks like it should be reverted

https://github.com/Uberi/Yunit/issues/31

**Comment by hoppfrosch** [comment]
My fix seemed to have worked at the time I fixed it. Haven't used YUnit recently, so I don't know if the fix is still valid- but obviously not ... ;-)
